# Generated by Django 5.2.8 on 2025-11-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="focussession",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="focussession",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("normal", "普通"), ("important", "重要")],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="moodrecord",
            name="mood",
            field=models.IntegerField(),
        ),
    ]
