# Generated by Django 5.2.8 on 2025-11-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_focussession_ended_at_focussession_started_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmbientSound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("key", models.SlugField(blank=True, max_length=120, unique=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="sounds/")),
                ("file_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
