# Generated by Django 5.2.8 on 2025-11-28 07:47

from django.db import migrations


def seed_sounds(apps, schema_editor):
    AmbientSound = apps.get_model("core", "AmbientSound")
    defaults = [
        {
            "name": "雨声 Rain",
            "key": "rain",
            "file_url": "/media/sounds/rain.mp3",
        },
        {
            "name": "海边 Sea",
            "key": "sea",
            "file_url": "/media/sounds/sea.mp3",
        },
        {
            "name": "咖啡馆 Cafe",
            "key": "cafe",
            "file_url": "/media/sounds/cafe.mp3",
        },
    ]
    for data in defaults:
        AmbientSound.objects.get_or_create(key=data["key"], defaults=data)


def remove_seeded_sounds(apps, schema_editor):
    AmbientSound = apps.get_model("core", "AmbientSound")
    AmbientSound.objects.filter(key__in=["rain", "sea", "cafe"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_ambientsound"),
    ]

    operations = [migrations.RunPython(seed_sounds, remove_seeded_sounds)]
