# Generated by Django 5.2.8 on 2025-11-28 14:12

from django.db import migrations
from django.db.models import Q


def unpublish_external_sounds(apps, schema_editor):
    AmbientSound = apps.get_model("core", "AmbientSound")
    AmbientSound.objects.filter(
        Q(file__isnull=True) | Q(file=""),
        file_url__startswith="http",
    ).update(is_published=False)


def restore_external_sounds(apps, schema_editor):
    AmbientSound = apps.get_model("core", "AmbientSound")
    AmbientSound.objects.filter(file_url__startswith="http").update(is_published=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_gardenitem_and_duration"),
    ]

    operations = [migrations.RunPython(unpublish_external_sounds, restore_external_sounds)]
