# Generated by Django 5.2.8 on 2025-11-28 14:45

from django.db import migrations


SOUND_DEFINITIONS = [
    {
        "key": "none",
        "name": "无声",
        "file_url": "",
        "is_published": True,
    },
    {
        "key": "meditation",
        "name": "冥想",
        "file_url": "/media/sounds/meditation.mp3",
        "is_published": True,
    },
    {
        "key": "ktv",
        "name": "酒吧KTV",
        "file_url": "/media/sounds/ktv.mp3",
        "is_published": True,
    },
]


def configure_sounds(apps, schema_editor):
    AmbientSound = apps.get_model("core", "AmbientSound")
    allowed_keys = [sound["key"] for sound in SOUND_DEFINITIONS]
    AmbientSound.objects.exclude(key__in=allowed_keys).update(is_published=False)
    for sound in SOUND_DEFINITIONS:
        AmbientSound.objects.update_or_create(key=sound["key"], defaults=sound)


def restore_sounds(apps, schema_editor):
    AmbientSound = apps.get_model("core", "AmbientSound")
    AmbientSound.objects.filter(key__in=["none", "meditation", "ktv"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_unpublish_external_sounds"),
    ]

    operations = [migrations.RunPython(configure_sounds, restore_sounds)]
